import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1',
      items: ['chapter1'],
    },
    {
      type: 'category',
      label: 'Module 2',
      items: ['chapter2'],
    },
    {
      type: 'category',
      label: 'Module 3',
      items: ['chapter3'],
    },
    {
      type: 'category',
      label: 'Module 4',
      items: ['chapter4'],
    },
    {
      type: 'category',
      label: 'Module 5',
      items: ['chapter5'],
    },
    {
      type: 'category',
      label: 'Module 6',
      items: ['chapter6'],
    },
    {
      type: 'category',
      label: 'Module 7',
      items: ['chapter7'],
    },
    {
      type: 'category',
      label: 'Module 8',
      items: ['chapter8'],
    },
    {
      type: 'category',
      label: 'Module 9',
      items: ['chapter9'],
    },
    {
      type: 'category',
      label: 'Module 10',
      items: ['chapter10'],
    },
    {
      type: 'category',
      label: 'Module 11',
      items: ['chapter11'],
    },
    {
      type: 'category',
      label: 'Module 12',
      items: ['chapter12'],
    },
    {
      type: 'category',
      label: 'Module 13',
      items: ['chapter13'],
    },
    {
      type: 'category',
      label: 'Module 14',
      items: ['chapter14'],
    },
    {
      type: 'category',
      label: 'Module 15',
      items: ['chapter15'],
    },
    {
      type: 'category',
      label: 'Module 16',
      items: ['chapter16'],
    },
  ],
};

export default sidebars;
