import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Part 1: Foundations',
      items: [
        {
          type: 'doc',
          id: 'part1-foundations/chap1',
        },
        {
          type: 'doc',
          id: 'part1-foundations/chap2',
        },
        {
          type: 'doc',
          id: 'part1-foundations/chap3',
        },
        {
          type: 'doc',
          id: 'part1-foundations/chap4',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part 2: Perception & Actuation',
      items: [
        {
          type: 'doc',
          id: 'part2-perception-actuation/chap5',
        },
        {
          type: 'doc',
          id: 'part2-perception-actuation/chap6',
        },
        {
          type: 'doc',
          id: 'part2-perception-actuation/chap7',
        },
        {
          type: 'doc',
          id: 'part2-perception-actuation/chap8',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part 3: Intelligence & Learning',
      items: [
        {
          type: 'doc',
          id: 'part3-intelligence-learning/chap9',
        },
        {
          type: 'doc',
          id: 'part3-intelligence-learning/chap10',
        },
        {
          type: 'doc',
          id: 'part3-intelligence-learning/chap11',
        },
        {
          type: 'doc',
          id: 'part3-intelligence-learning/chap12',
        },
      ],
    },
    {
      type: 'category',
      label: 'Part 4: Advanced Topics',
      items: [
        {
          type: 'doc',
          id: 'part4-advanced-topics/chap13',
        },
        {
          type: 'doc',
          id: 'part4-advanced-topics/chap14',
        },
        {
          type: 'doc',
          id: 'part4-advanced-topics/chap15',
        },
        {
          type: 'doc',
          id: 'part4-advanced-topics/chap16',
        },
      ],
    },
  ],
};

export default sidebars;
