import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'part1-foundations', // Generates a sidebar from the docs/part1-foundations folder
    },
    {
      type: 'autogenerated',
      dirName: 'part2-perception-actuation', // Generates a sidebar from the docs/part2-perception-actuation folder
    },
    {
      type: 'autogenerated',
      dirName: 'part3-intelligence-learning', // Generates a sidebar from the docs/part3-intelligence-learning folder
    },
    {
      type: 'autogenerated',
      dirName: 'part4-advanced-topics', // Generates a sidebar from the docs/part4-advanced-topics folder
    },


  ],
};

export default sidebars;
